In [3]:
import numpy as np

In [4]:
import pandas as pd

In [4]:
 arr =np.array([1,2,3,4,5])
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [6]:
arr.ndim

1

In [7]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
data=np.random.randint(1,10,(4,4))

In [10]:
np.max(data)

9

In [11]:
np.max(data,axis=1)

array([9, 7, 6, 8])

In [12]:
np.log(data)

array([[1.60943791, 2.19722458, 1.94591015, 2.19722458],
       [1.09861229, 0.        , 1.09861229, 1.94591015],
       [1.09861229, 1.38629436, 1.79175947, 0.69314718],
       [1.94591015, 2.07944154, 1.79175947, 1.38629436]])

In [13]:
np.sort(data,axis=1)

array([[5, 7, 9, 9],
       [1, 3, 3, 7],
       [2, 3, 4, 6],
       [4, 6, 7, 8]])

In [14]:
np.sort(data)

array([[5, 7, 9, 9],
       [1, 3, 3, 7],
       [2, 3, 4, 6],
       [4, 6, 7, 8]])

In [15]:
np.log10(data)

array([[0.69897   , 0.95424251, 0.84509804, 0.95424251],
       [0.47712125, 0.        , 0.47712125, 0.84509804],
       [0.47712125, 0.60205999, 0.77815125, 0.30103   ],
       [0.84509804, 0.90308999, 0.77815125, 0.60205999]])

In [17]:
np.matmul(data,data)

array([[136, 154, 158, 158],
       [ 76,  96,  84,  68],
       [ 59,  71,  81,  75],
       [105, 127, 133, 147]])

In [18]:
np.linalg.inv(data)

array([[-0.21910112,  0.15168539, -0.09550562,  0.2752809 ],
       [ 0.17696629, -0.1994382 , -0.11516854,  0.00842697],
       [-0.03651685,  0.0252809 ,  0.31741573, -0.12078652],
       [ 0.08426966,  0.09550562, -0.07865169, -0.06741573]])

In [19]:
data+data

array([[10, 18, 14, 18],
       [ 6,  2,  6, 14],
       [ 6,  8, 12,  4],
       [14, 16, 12,  8]])

In [41]:
x = np.zeros(10)
x[5] = 1
x[-1]=10
print(x)

[ 0.  0.  0.  0.  0.  1.  0.  0.  0. 10.]


In [42]:
rev=x[::-1]
print(rev)


[10.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [54]:
#Create a 3x3 matrix with values ranging from 0 to 8
data=np.random.randint(0,9,(3,3,3))
data

array([[[6, 8, 5],
        [5, 4, 7],
        [4, 6, 5]],

       [[8, 5, 0],
        [2, 7, 3],
        [1, 6, 0]],

       [[2, 5, 6],
        [5, 0, 0],
        [1, 8, 8]]])

In [55]:
np.sum(data,axis=0)

array([[16, 18, 11],
       [12, 11, 10],
       [ 6, 20, 13]])

In [53]:
np.random.randint(0,10,(16,16))


array([[1, 1, 3, 5, 7, 7, 0, 7, 4, 7, 2, 3, 9, 9, 5, 7],
       [4, 4, 9, 6, 7, 4, 6, 0, 1, 7, 5, 7, 8, 1, 1, 9],
       [1, 0, 1, 2, 3, 6, 8, 2, 3, 3, 6, 5, 8, 9, 2, 0],
       [9, 5, 9, 9, 5, 6, 6, 6, 6, 4, 0, 1, 0, 9, 3, 7],
       [0, 2, 1, 4, 5, 3, 3, 2, 2, 9, 9, 2, 8, 2, 8, 4],
       [5, 7, 2, 0, 4, 6, 8, 2, 9, 6, 3, 6, 3, 1, 1, 5],
       [9, 7, 9, 0, 6, 5, 2, 8, 0, 4, 1, 2, 5, 2, 3, 4],
       [1, 5, 7, 9, 8, 8, 8, 7, 3, 1, 8, 1, 0, 4, 5, 7],
       [8, 4, 2, 4, 9, 1, 7, 6, 1, 8, 9, 3, 5, 3, 8, 1],
       [2, 9, 2, 6, 6, 5, 8, 8, 6, 5, 1, 5, 4, 7, 4, 5],
       [5, 7, 5, 7, 4, 5, 8, 7, 4, 6, 2, 5, 8, 2, 7, 4],
       [9, 2, 9, 8, 7, 4, 8, 7, 5, 2, 3, 7, 2, 4, 2, 1],
       [5, 2, 2, 9, 4, 4, 6, 0, 8, 2, 8, 5, 9, 5, 8, 6],
       [1, 7, 6, 3, 0, 0, 8, 0, 9, 3, 6, 9, 4, 4, 3, 2],
       [4, 0, 7, 6, 1, 8, 1, 4, 5, 0, 8, 9, 9, 8, 8, 0],
       [3, 4, 7, 9, 6, 5, 1, 2, 1, 5, 6, 8, 8, 8, 4, 1]])

In [82]:
data=np.random.randint(0,10,(16,16))

In [83]:
res[0,0]=np.sum(data[:4,:4])


In [84]:
res[0,1]=np.sum(data[:4,4:8])
res[0,2]=np.sum(data[:4,8:12])
res[0,3]=np.sum(data[:4,12:16])
res

array([[62., 68., 86., 60.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [85]:
for i in range(4):
    for j in range(4):
        res[i,j]=np.sum(data[i*4:i*4+4,j*4:j*4+4])
        print(res)
    

[[62. 68. 86. 60.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[62. 68. 86. 60.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[62. 68. 86. 60.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[62. 68. 86. 60.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[62. 68. 86. 60.]
 [89.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[62. 68. 86. 60.]
 [89. 76.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[62. 68. 86. 60.]
 [89. 76. 74.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[62. 68. 86. 60.]
 [89. 76. 74. 65.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[62. 68. 86. 60.]
 [89. 76. 74. 65.]
 [68.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[62. 68. 86. 60.]
 [89. 76. 74. 65.]
 [68. 68.  0.  0.]
 [ 0.  0.  0.  0.]]
[[62. 68. 86. 60.]
 [89. 76. 74. 65.]
 [68. 68. 92.  0.]
 [ 0.  0.  0.  0.]]
[[62. 68. 86. 60.]
 [89. 76. 74. 65.]
 [68. 68. 92. 73.]
 [ 0.  0.  0.  0.]]
[[62. 68. 86. 60.]
 [89. 76. 74. 65.]
 [68. 68. 92. 73.]
 [81.  0.  0.  0.]]

In [86]:
#np.hsplit(data,[8]) #horizontal split
res=np.vsplit(data,[4,8,12])

[array([[9, 1, 6, 0, 2, 6, 3, 8, 2, 8, 7, 3, 2, 9, 7, 2],
        [8, 4, 0, 9, 7, 6, 3, 9, 5, 1, 8, 8, 4, 2, 0, 8],
        [0, 5, 0, 3, 1, 0, 7, 6, 3, 9, 7, 8, 0, 5, 2, 3],
        [5, 4, 3, 5, 7, 0, 2, 1, 2, 7, 3, 5, 6, 5, 0, 5]]),
 array([[2, 8, 0, 6, 2, 2, 6, 7, 4, 7, 4, 7, 7, 4, 3, 9],
        [7, 9, 2, 5, 0, 5, 5, 4, 5, 5, 0, 6, 9, 0, 2, 6],
        [3, 4, 8, 3, 9, 5, 0, 4, 4, 5, 4, 3, 4, 2, 4, 1],
        [9, 7, 8, 8, 7, 6, 5, 9, 5, 6, 3, 6, 0, 1, 6, 7]]),
 array([[2, 7, 6, 7, 0, 3, 3, 3, 4, 6, 7, 7, 7, 2, 9, 0],
        [4, 2, 2, 8, 3, 8, 9, 5, 6, 6, 9, 7, 5, 5, 1, 4],
        [1, 8, 6, 3, 1, 0, 5, 7, 9, 5, 8, 5, 8, 7, 0, 2],
        [0, 0, 7, 5, 0, 8, 5, 8, 8, 0, 5, 0, 7, 7, 3, 6]]),
 array([[6, 2, 3, 3, 5, 5, 5, 2, 4, 9, 7, 1, 8, 5, 1, 8],
        [3, 8, 0, 5, 8, 5, 2, 6, 3, 8, 0, 4, 4, 9, 6, 5],
        [9, 2, 7, 9, 3, 1, 2, 7, 4, 0, 0, 0, 1, 2, 5, 7],
        [2, 5, 8, 9, 3, 8, 7, 9, 3, 9, 7, 4, 1, 6, 3, 5]])]

In [10]:
res=[]
for e in res:
    res.extend(np.hsplit(e,[4,8,12])
print(res)    

SyntaxError: invalid syntax (<ipython-input-10-0ad7e2d83f4a>, line 4)

In [ ]:
fin=[]
for r in res:
    fin.append(np.sum(r))
    

In [11]:
titanic=pd.read_csv('https://raw.githubusercontent.com/zekelabs/data-science-complete-tutorial/master/Data/titanic-train.csv.txt',index_col='PassengerId')

In [12]:
titanic[:4]

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S